assistant_register:
  path: /
  controller: App\Controller\AssistantController::new

assistant_success:
  path: /success
  controller: App\Controller\AssistantController::success

assistant_category_full:
  path: /category-full
  controller: App\Controller\AssistantController::categoryFull